### ISSUE TITLE
Guide for use in Windows?

### ISSUE THREAD

**Issue by valzi** [Jack000/Expose-2.0#45]
The current readme doesn't seem to describe what to do in Windows. How do I generate a site?

**Comment by r0n0c** [comment]
Out of the box you cannot run this on windows, you need a bash environment. It says you need Cygwin with Windows because Cygwin gives you a bash interface. This runs a bash script. Another option in win10 is running [Linux on Windows with Ubuntu from the MS Store](https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q).

**Comment by valzi** [comment]
Thanks!
